### PR TITLE
Adding DataKitchen related sites

### PR DESCRIPTION
**Pull request by cbergh**

### CODE REVIEW

**Comment by stephlocke** [comment]
Heya Chris, any reason for the delete?

**Comment by stephlocke** [comment]
@cbergh Merged in the pics but need these files - do you want both coming in? Or just the one that hasn't been deleted?

**Comment by cbergh** [comment]
My apologies ... I wanted to add both the DataKitchen and DataOps blog as two separate widgets/blocks

**Comment by stephlocke** [comment]
Added in. The images could do with being a bit bigger if you want the entries to look a bit nicer but otherwise, all done!

**Pull request merged**
